### ISSUE TITLE
Two "os" for one "device"

### ISSUE THREAD

**Issue by extsoft** [CiscoTestAutomation/pyats#10]
According to 
https://pubhub.devnetcloud.com/media/pyats-packages/docs/unicon/user_guide/connection.html#how-to-connect-in-pyats-environment-using-testbed-file, I can define a device within a testbed file in a following way:
```yaml
my-server:
    os: 'linux'
    type: 'linux'
    connections:
      a:
        protocol: telnet
        ip: 10.64.70.11
        port: 2042
```
And I have a device which has two different `os` installed on it at the same time.

Is there a chance to specify one more connection with another `os`?

**Comment by siming85** [comment]
the ``os`` field in testbed yaml is used for a few things:

1. for Unicon to pick up the right connection plugin/implementation
2. for Genie to pick up the right set of abstraction libraries.

it's really an arbitrary string, so it's entirely possible to use what-you-wish as a field that matters to you, with the above constrictions in mind.

you can add your other os under ``custom:`` field for your own reference.

i think the real challenge would be if you have TWO os in the device, and you had the ability to switch it post-connection, and if that alters the actual device prompts and behavior (eg, in Unicon's terms, statemachine), it would break the logic.

**Comment by extsoft** [comment]
> i think the real challenge would be if you have TWO os in the device, and you had the ability to switch it post-connection, and if that alters the actual device prompts and behavior (eg, in Unicon's terms, statemachine), it would break the logic.

I have this case. I need something like this:
```yaml
my-server:
    type: 'linux'
    connections:
      a:
        os: 'linux'
        protocol: telnet
        ip: 10.64.70.11
        port: 2042
     b:
        os: 'cimc'
        protocol: ssh
        ip: 10.64.70.11
        port: 2041
```
And then
```pyhon
...
device.connect(via=a, alias='a')
device.connect(via=b, alias='b')
...
```

If I understand correctly, it is not possible right now. Is there an alternative to do this?
