### ISSUE TITLE
pyats.topology.loader: Error while loading when the testbed name consists solely of numbers?

### ISSUE THREAD

**Issue by Sulray** [CiscoTestAutomation/pyats#250]
I had a really weird issue today.

I wanted to use the following testbed :
``` yaml
devices:
  c106-clients:
    alias: c106-clients
    connections:
      rest:
        class: rest.connector.Rest
        ip: c106-clients
        port: 443
        protocol: https
    custom:
      abstraction:
        order:
        - os
    os: bigip
testbed:
  credentials:
    default:
      password: '%ASK{}'
      username: user1
  name: 4347799
```

The name of my testbed here is "4347799", important detail.

I tried to load the testbed as usual like that, with the testbed_path leading to the yaml file of my testbed : 
``` python
    # from pyats.topology.loader import load
    def loadTestbed(self):
        try:
            self.testbed = load(self.testbed_path)
            logger.critical("Managed to load testbed correctly")
        except:
            logger.critical("Testbed is not resolved, didn't manage to load testbed correctly")
```
And it led to the following logs : 

> 2024-09-25 09:20:17,776 - __main__ - INFO - Starting loadTestbed() (main.py:62)
> 2024-09-25 09:20:17,776 - pyats.utils.yaml.loader - DEBUG - loading yaml file /home/user1/project/testbeds/testbed_4347799.yaml (__init__.py:44)
> Enter default password for testbed: 
> 2024-09-25 09:20:21,705 - pyats.utils.secret_strings - DEBUG - Using a default key as pyATS configuration under [secrets] string.key was not specified. (__init__.py:44)
> 2024-09-25 09:20:21,705 - pyats.utils.secret_strings - DEBUG - Using a default key as pyATS configuration under [secrets] string.key was not specified. (__init__.py:44)
> 2024-09-25 09:20:21,706 - custom_package.operation - CRITICAL - Testbed is not resolved, didn't manage to load testbed correctly (operation.py:376)

At this point I was already kind of lost since I didn't understand why it was leading to an issue.

Then I tried to change the testbed name to "4347799A", adding a "A" at the end. And it worked :O

> 2024-09-25 09:19:49,196 - __main__ - INFO - Starting loadTestbed() (main.py:62)
> 2024-09-25 09:19:49,196 - pyats.utils.yaml.loader - DEBUG - loading yaml file /home/user1/project/testbeds/testbed_4347799A.yaml (__init__.py:44)
> Enter default password for testbed: 
> 2024-09-25 09:19:53,456 - pyats.utils.secret_strings - DEBUG - Using a default key as pyATS configuration under [secrets] string.key was not specified. (__init__.py:44)
> 2024-09-25 09:19:53,456 - pyats.utils.secret_strings - DEBUG - Using a default key as pyATS configuration under [secrets] string.key was not specified. (__init__.py:44)
> 2024-09-25 09:19:53,621 - pyats.topology.credentials - DEBUG - Credential credentials not found, trying default ... (__init__.py:44)
> 2024-09-25 09:19:53,622 - custom_package.operation - CRITICAL - Managed to load testbed correctly (operation.py:374)

Is there a known rule prohibiting testbed names from consisting solely of numbers? 
I need some help with that.

I'm using pyats.topology 24.5 but I don't think it has been corrected since no issues were about that subject.
