### ISSUE TITLE
Are there any exit_commands?

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/pyats#35]
I are there any property that can be run when i exit/disconnect from a device?

When we connect we can use 

```
devices:
    mydevice:
        connections:
            vty:
                init_config_commands: []
                init_exec_commands: []
```
