### ISSUE TITLE
pyATS Ping function seems not work properly. 

### ISSUE THREAD

**Issue by mahoutukaisali** [CiscoTestAutomation/pyats#36]
Hi.

I'm trying to develop the ping testcase between ios devices using script following below but it seems work incorrectly.
This script return the result with "Failed reason: Ping 172.20.0.22 from device r1 failed with error: 'r1'" BUT pinging to 172.20.0.22 from device r1 is reachable in actual status.

Could someone please give me some solutions or advises?

Thanks.

connection_check.py
```
# Example
# -------
#
#   connectivity_check.py

from pyats import aetest

class CommonSetup(aetest.CommonSetup):

    @aetest.subsection
    def check_topology(self,
                       testbed,
                       ios1_name = 'r1',
                       ios2_name = 'r2'):
        ios1 = testbed.devices[ios1_name]
        ios2 = testbed.devices[ios2_name]

        # add them to testscript parameters
        self.parent.parameters.update(ios1 = ios1, ios2 = ios2)

        # get corresponding links
        links = ios1.find_links(ios2)

        assert len(links) >= 1, 'require one link between ios1 and ios2'


    @aetest.subsection
    def establish_connections(self, steps, ios1, ios2):
        with steps.start('Connecting to %s' % ios1.name):
            ios1.connect()

        with steps.start('Connecting to %s' % ios1.name):
            ios2.connect()

@aetest.loop(device = ('r1', 'r2'))
class PingTestcase(aetest.Testcase):

    @aetest.test.loop(destination = ('172.20.0.22', '172.20.0.21'))
    def ping(self, device, destination):
        try:
            result = self.parameters[device].ping(destination)

        except Exception as e:
            self.failed('Ping {} from device {} failed with error: {}'.format(
                                destination,
                                device,
                                str(e),
                            ),
                        goto = ['exit'])
        else:
            match = re.search(r'Success rate is (?P<rate>\d+) percent', result)
            success_rate = match.group('rate')

            logger.info('Ping {} with success rate of {}%'.format(
                                        destination,
                                        success_rate,
                                    )
                               )
(snip)
```

 testbed.yaml
```
testbed:
  name: pyATS_IOS_Example_Testbed
devices:
  r1:
    alias: r1
    os: iosxe
    type: router
    connections:
      defaults:
        class: 'unicon.Unicon'
      ssh:
        protocol: ssh
        ip: 172.20.0.21
        port: 22
    credentials:
      default:
        username: cisco
        password: cisco
        enable: cisco

  r2:
    alias: r2
    os: iosxe
    type: router
    connections:
      defaults:
        class: 'unicon.Unicon'
      ssh:
        protocol: ssh
        ip: 172.20.0.22
        port: 22
    credentials:
      default:
        username: cisco
        password: cisco
        enable: cisco
topology:
  r1:
    interfaces:
      GigabitEthernet2:
        ipv4: 172.20.0.21/16
        link: link
        type: gigabitethernet
      Loopback0:
        ipv4: 192.168.254.1/32
        link: ios1_Loopback0
        type: loopback
  r2:
    interfaces:
      GigabitEthernet2:
        ipv4: 172.20.0.22/16
        link: link
        type: gigabitethernet
      Loopback0:
        ipv4: 192.168.254.2/32
        link: ios2_Loopback0
        type: loopback


```
